app.version: 2.0
app.author: Duong Thai Minh

nship: 10

players.dir: player

judge_config_file: /home/ferez96/Projects/HauDuePascal/Round-3/battleship-server/config/judge.config.yaml

webserver:
  port: 18080